// Generated by tools/tides/generate-nazare-tide-data.mjs. Do not edit manually.
#pragma once

#include "tides/TideEngine.h"

namespace TideDevelopmentData
{
// Development-only station data licensed CC BY-NC 4.0.
extern const TideHarmonicStation nazare;
}
