// Generated by tools/tides/generate-nazare-tide-data.mjs. Do not edit manually.
// Source: tools/tides/generated/portugal-stations.json
#include "NazareTideData.h"

namespace
{
// Development-only data. The first eight entries are the historical major-
// constituent baseline used by the host comparison tests.
constexpr TideConstituent constituents[] = {
    // amplitude (m), phase UTC (degrees), Doodson coefficients, IHO nodal terms
    {0.98384380f, 70.351053f, {2, 0, 0, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M2
    {0.21418306f, 52.312497f, {2, -1, 0, 1, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // N2
    {0.34218614f, 98.583019f, {2, 2, -2, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // S2
    {0.09034627f, 92.522527f, {2, 2, 0, 0, 0, 0, 0}, {{TideNodalFundamental::K2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // K2
    {0.06771514f, 60.363795f, {1, 1, 0, 0, 0, 0, -1}, {{TideNodalFundamental::K1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // K1
    {0.02130731f, 48.719153f, {1, 1, -2, 0, 0, 0, 1}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // P1
    {0.06058316f, 318.159164f, {1, -1, 0, 0, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // O1
    {0.01904336f, 269.046716f, {1, -2, 0, 1, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // Q1
    {0.03118438f, 36.303814f, {2, -2, 0, 2, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 2N2
    {0.00412048f, 359.370662f, {1, 1, -1, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // S1
    {0.00164899f, 208.440308f, {1, 0, 0, 1, 0, 0, -1}, {{TideNodalFundamental::M1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M1
    {0.00830327f, 199.171541f, {4, 0, 0, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M4
    {0.00384293f, 240.609884f, {0, 1, 0, -1, 0, 0, 0}, {{TideNodalFundamental::Mm, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MM (Neaps: Mm)
    {0.00197323f, 60.287030f, {0, 2, 0, 0, 0, 0, 0}, {{TideNodalFundamental::Mf, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MF (Neaps: Mf)
    {0.02944564f, 206.226374f, {0, 0, 1, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // SA (Neaps: Sa)
    {0.03986875f, 73.008869f, {0, 0, 2, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // SSA (Neaps: Ssa)
    {0.02308208f, 113.415101f, {2, 2, -3, 0, 0, 1, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // T2
    {0.00169025f, 82.485871f, {1, 2, 0, -1, 0, 0, -1}, {{TideNodalFundamental::J1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // J1
    {0.01953726f, 88.747155f, {2, 1, 0, -1, 0, 0, -2}, {{TideNodalFundamental::L2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // L2
    {0.00790140f, 148.893799f, {2, 2, -1, 0, 0, -1, -2}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // R2
    {0.00390443f, 220.697556f, {1, -3, 0, 2, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 2Q1
    {0.00551013f, 81.960627f, {0, 2, -2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, -1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MSF (Neaps: MSf)
    {0.00219717f, 321.083655f, {0, 4, -2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, -1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MSQM (Neaps: MSqm)
    {0.01144775f, 2.703682f, {2, -3, 2, 1, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // EP2 (Neaps: eps2)
    {0.00462980f, 287.080906f, {3, 0, 0, 0, 0, 0, -2}, {{TideNodalFundamental::M3, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M3
    {0.03842136f, 28.326342f, {2, -2, 2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MU2 (Neaps: mu2)
    {0.00200808f, 69.211443f, {0, 3, 0, -1, 0, 0, 0}, {{TideNodalFundamental::Mm, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MTM (Neaps: Mfm)
    {0.03859664f, 60.013827f, {2, -1, 2, -1, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // NU2 (Neaps: nu2)
    {0.00490244f, 140.782033f, {2, 1, -2, 1, 0, 0, -2}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // LAMBDA2 (Neaps: lambda2)
    {0.00318170f, 149.808649f, {4, -1, 0, 1, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::M2, 1.00f}}, 2}, // MN4
    {0.00489900f, 279.615943f, {4, 2, -2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MS4
    {0.01828113f, 307.670027f, {2, 0, 2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::K2, 1.00f}}, 2}, // MKS2
    {0.00083505f, 71.374889f, {4, -2, 0, 2, 0, 0, 0}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // N4
    {0.00176661f, 144.501288f, {6, 0, 0, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 3.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M6
    {0.00010491f, 187.384383f, {8, 0, 0, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 4.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M8
    {0.00081458f, 306.033593f, {4, 4, -4, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // S4
    {0.00384015f, 206.376688f, {1, 3, 0, 0, 0, 0, -1}, {{TideNodalFundamental::K2, 1.00f}, {TideNodalFundamental::O1, -1.00f}}, 2}, // OO1
    {0.00165807f, 45.433601f, {3, 3, -3, 0, 0, 0, -2}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // S3
    {0.01660308f, 245.502856f, {2, 0, -1, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // MA2
    {0.00838207f, 318.656345f, {2, 0, 1, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // MB2
    {0.00172587f, 101.767269f, {3, 3, -4, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // T3
    {0.00282114f, 266.959153f, {3, 3, -2, 0, 0, 0, -1}, {{TideNodalFundamental::K1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // R3 (Neaps: SK3)
    {0.00261284f, 277.142783f, {1, -2, 2, -1, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // RHO1 (Neaps: rho1)
    {0.00395953f, 51.028897f, {1, -3, 2, 0, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // SGM (Neaps: sigma1)
    {0.00160148f, 172.599561f, {2, 1, 0, 0, 0, 0, 0}, {{TideNodalFundamental::L2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 3L2
    {0.00127779f, 193.872802f, {2, 0, 2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::K2, 1.00f}}, 2}, // 3N2 (Neaps: MKS2)
    {0.00830301f, 241.388295f, {2, 4, -4, 0, 0, 0, 0}, {{TideNodalFundamental::M2, -1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 2SM2
    {0.00228048f, 216.519469f, {6, 2, -2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 2MS6
    {0.00036424f, 264.040574f, {5, 1, 0, 0, 0, 0, -1}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::K1, 1.00f}}, 2}, // 2MK5
    {0.00022366f, 323.693737f, {5, -1, 0, 0, 0, 0, 1}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::O1, 1.00f}}, 2}, // 2MO5
};

static_assert(sizeof(constituents) / sizeof(constituents[0]) == 50,
              "Nazaré development dataset must contain 50 constituents");
} // namespace

namespace TideDevelopmentData
{
const TideHarmonicStation nazare = {
    "ticon/nazaretg-naz-prt-cmems",
    "Nazare",
    "TICON-4 via Neaps Tide Database",
    "CC BY-NC 4.0",
    constituents,
    sizeof(constituents) / sizeof(constituents[0]),
    true,
};
}
