// Generated by tools/tides/generate-peniche-tide-data.mjs. Do not edit manually.
// Source: tools/tides/generated/portugal-stations.json
#include "PenicheTideData.h"

namespace
{
// Development-only data. The first eight entries mirror the Nazaré major-
// constituent baseline used by the host comparison tests.
constexpr TideConstituent constituents[] = {
    // amplitude (m), phase UTC (degrees), Doodson coefficients, IHO nodal terms
    {1.02070944f, 69.186975f, {2, 0, 0, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M2
    {0.22269829f, 50.814611f, {2, -1, 0, 1, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // N2
    {0.35227046f, 97.288643f, {2, 2, -2, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // S2
    {0.09306646f, 92.452482f, {2, 2, 0, 0, 0, 0, 0}, {{TideNodalFundamental::K2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // K2
    {0.07528858f, 55.837270f, {1, 1, 0, 0, 0, 0, -1}, {{TideNodalFundamental::K1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // K1
    {0.02442507f, 45.004720f, {1, 1, -2, 0, 0, 0, 1}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // P1
    {0.06403898f, 315.403303f, {1, -1, 0, 0, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // O1
    {0.02007404f, 261.202779f, {1, -2, 0, 1, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // Q1
    {0.03248864f, 35.076769f, {2, -2, 0, 2, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 2N2
    {0.00420668f, 350.447654f, {1, 1, -1, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // S1
    {0.00170597f, 223.172551f, {1, 0, 0, 1, 0, 0, -1}, {{TideNodalFundamental::M1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M1
    {0.00856439f, 186.550177f, {4, 0, 0, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M4
    {0.00460022f, 264.707378f, {0, 1, 0, -1, 0, 0, 0}, {{TideNodalFundamental::Mm, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MM (Neaps: Mm)
    {0.00307675f, 354.632344f, {0, 2, 0, 0, 0, 0, 0}, {{TideNodalFundamental::Mf, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MF (Neaps: Mf)
    {0.03257716f, 205.596375f, {0, 0, 1, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // SA (Neaps: Sa)
    {0.04078708f, 79.163819f, {0, 0, 2, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // SSA (Neaps: Ssa)
    {0.02781625f, 103.818397f, {2, 2, -3, 0, 0, 1, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // T2
    {0.00225730f, 77.342709f, {1, 2, 0, -1, 0, 0, -1}, {{TideNodalFundamental::J1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // J1
    {0.01826074f, 83.262830f, {2, 1, 0, -1, 0, 0, -2}, {{TideNodalFundamental::L2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // L2
    {0.01126776f, 155.648831f, {2, 2, -1, 0, 0, -1, -2}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // R2
    {0.00378399f, 204.781419f, {1, -3, 0, 2, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 2Q1
    {0.00469949f, 67.925936f, {0, 2, -2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, -1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MSF (Neaps: MSf)
    {0.00282872f, 330.342174f, {0, 4, -2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, -1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MSQM (Neaps: MSqm)
    {0.01112484f, 359.191448f, {2, -3, 2, 1, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // EP2 (Neaps: eps2)
    {0.00494114f, 282.704882f, {3, 0, 0, 0, 0, 0, -2}, {{TideNodalFundamental::M3, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M3
    {0.03935649f, 24.600315f, {2, -2, 2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MU2 (Neaps: mu2)
    {0.00115990f, 154.888031f, {0, 3, 0, -1, 0, 0, 0}, {{TideNodalFundamental::Mm, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MTM (Neaps: Mfm)
    {0.04057609f, 55.751813f, {2, -1, 2, -1, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // NU2 (Neaps: nu2)
    {0.00760370f, 115.901843f, {2, 1, -2, 1, 0, 0, -2}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // LAMBDA2 (Neaps: lambda2)
    {0.00353427f, 138.427294f, {4, -1, 0, 1, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::M2, 1.00f}}, 2}, // MN4
    {0.00498902f, 272.311364f, {4, 2, -2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // MS4
    {0.01326723f, 301.248810f, {2, 0, 2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::K2, 1.00f}}, 2}, // MKS2
    {0.00124214f, 74.094512f, {4, -2, 0, 2, 0, 0, 0}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // N4
    {0.00174005f, 140.197524f, {6, 0, 0, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 3.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M6
    {0.00010664f, 166.784549f, {8, 0, 0, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 4.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // M8
    {0.00067690f, 288.203872f, {4, 4, -4, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // S4
    {0.00405185f, 206.275028f, {1, 3, 0, 0, 0, 0, -1}, {{TideNodalFundamental::K2, 1.00f}, {TideNodalFundamental::O1, -1.00f}}, 2}, // OO1
    {0.00156561f, 28.278594f, {3, 3, -3, 0, 0, 0, -2}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // S3
    {0.00954828f, 220.299468f, {2, 0, -1, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // MA2
    {0.01555385f, 266.637032f, {2, 0, 1, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // MB2
    {0.00232856f, 94.678917f, {3, 3, -4, 0, 0, 0, 0}, {{TideNodalFundamental::None, 0.00f}, {TideNodalFundamental::None, 0.00f}}, 0}, // T3
    {0.00285794f, 255.718332f, {3, 3, -2, 0, 0, 0, -1}, {{TideNodalFundamental::K1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // R3 (Neaps: SK3)
    {0.00293621f, 257.456962f, {1, -2, 2, -1, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // RHO1 (Neaps: rho1)
    {0.00391978f, 40.797149f, {1, -3, 2, 0, 0, 0, 1}, {{TideNodalFundamental::O1, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // SGM (Neaps: sigma1)
    {0.00479770f, 158.709783f, {2, 1, 0, 0, 0, 0, 0}, {{TideNodalFundamental::L2, 1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 3L2
    {0.00435461f, 59.443692f, {2, 0, 2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 1.00f}, {TideNodalFundamental::K2, 1.00f}}, 2}, // 3N2 (Neaps: MKS2)
    {0.01118086f, 243.456749f, {2, 4, -4, 0, 0, 0, 0}, {{TideNodalFundamental::M2, -1.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 2SM2
    {0.00231719f, 213.007857f, {6, 2, -2, 0, 0, 0, 0}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::None, 0.00f}}, 1}, // 2MS6
    {0.00051965f, 239.425031f, {5, 1, 0, 0, 0, 0, -1}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::K1, 1.00f}}, 2}, // 2MK5
    {0.00010415f, 232.009404f, {5, -1, 0, 0, 0, 0, 1}, {{TideNodalFundamental::M2, 2.00f}, {TideNodalFundamental::O1, 1.00f}}, 2}, // 2MO5
};

static_assert(sizeof(constituents) / sizeof(constituents[0]) == 50,
              "Peniche development dataset must contain 50 constituents");
} // namespace

namespace TideDevelopmentData
{
const TideHarmonicStation peniche = {
    "ticon/penichetg-pen-prt-cmems",
    "Peniche",
    "TICON-4 via Neaps Tide Database",
    "CC BY-NC 4.0",
    constituents,
    sizeof(constituents) / sizeof(constituents[0]),
    true,
};
}
